FROM node:18-alpine

WORKDIR /usr/src/app

# Instala dependencias usando la cache
COPY package*.json ./
RUN npm ci

# Copia el resto del código
COPY . .

ENV PORT=3000
EXPOSE 3000

CMD ["npm","start"]
